Bludata/Bludata/Models/Estado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MySqlASPNetMVC.Models
{
    public class Estado
    {
        public int Id { get; set; }
        public string DS_ESTADO { get; set; }
        public string DS_SIGLA { get; set; }
    }
}

Bludata/Bludata/Controllers/EstadoController.cs
using MySqlASPNetMVC.Aplicacao;
using MySqlASPNetMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MySqlASPNetMVC.Controllers
{
    public class EstadoController : Controller
    {
        private EstadoAplicacao EmpresaAplicacao;
        public EstadoController()
        {
            EmpresaAplicacao = new EstadoAplicacao();
        }
        public ActionResult Index()
        {
            var lista = EmpresaAplicacao.ListarTodos();
            return View(lista);
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Estado estado)
        {
            if (ModelState.IsValid)
            {
                EmpresaAplicacao.Salvar(estado);
                return RedirectToAction("Index");
            }
            return View(estado);
        }

        public ActionResult Editar(int CD_ESTADO)
        {
            var estado = EmpresaAplicacao.ListarPorId(CD_ESTADO);

            if (estado == null)
                return HttpNotFound();

            return View(estado);
        }

        [HttpPost]
        public ActionResult Editar(Estado estado)
        {
            if (ModelState.IsValid)
            {
                EmpresaAplicacao.Salvar(estado);
                return RedirectToAction("Index");
            }
            return View(estado);
        }

        public ActionResult Detalhe(int CD_ESTADO)
        {
            var estado = EmpresaAplicacao.ListarPorId(CD_ESTADO);

            if (estado == null)
                return HttpNotFound();

            return View(estado);
        }

        public ActionResult Excluir(int CD_ESTADO)
        {
            var estado = EmpresaAplicacao.ListarPorId(CD_ESTADO);

            if (estado == null)
                return HttpNotFound();

            return View(estado);
        }

        [HttpPost, ActionName("Excluir")]
        public ActionResult ConfirmarExcluir(int CD_ESTADO)
        {
            EmpresaAplicacao.Excluir(CD_ESTADO);
            return RedirectToAction("Index");
        }
    }
}

Bludata/Bludata/Views/Estado/Cadastrar.cshtml
@model MySqlASPNetMVC.Models.Estado
@{
    ViewBag.Title = "Cadastrar Estado";
}

<div class="page-header">
    <h1>Estado <small>organize o cadastro de estados</small></h1>
</div>

<form method="POST" action="">
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Nova Estado</legend>
        <div class="form-group">
            <label for="Nome">Nome da Estado</label>
            <input id="Nome" name="Nome" type="text" class="form-control" placeholder="Digite o nome da Estado">
            @Html.ValidationMessageFor(x => x.DS_ESTADO)
        </div>

        <hr />
        <p>
            <button type="submit" class="btn btn-sm btn-info">Salvar</button>
            <a href="@Url.Action("Index","Home")">Cancelar</a>
        </p>
    </fieldset>
</form>

Bludata/Bludata/Views/Estado/Detalhe.cshtml
@model MySqlASPNetMVC.Models.Estado
@{
    ViewBag.Title = "Detalhe Estado";
}

<div class="page-header">
    <h1>Estado <small>organize o cadastro de estados</small></h1>
    <a href="@Url.Action("Cadastrar","Estado")" class="btn btn-sm btn-primary">Nova Estado</a>
</div>

<fieldset>
    <legend>Detalhes da Estado</legend>
    <div class="form-group">
        <strong>Nome: </strong> @Model.DS_ESTADO
    </div>
</fieldset>

<hr />
<p>
    <a href="@Url.Action("Editar","Home", new{Id=Model.CD_ESTADO})" class="btn btn-sm btn-info">Editar</a>
    <a href="@Url.Action("Index","Home")">Voltar</a>
</p>

Bludata/Bludata/Views/Estado/Editar.cshtml
@model MySqlASPNetMVC.Models.Estado
@{
    ViewBag.Title = "Editar Estado";
}

<div class="page-header">
    <h1>Estado <small>organize o cadastro de estados</small></h1>
    <a href="@Url.Action("Cadastrar","Estado")" class="btn btn-sm btn-primary">Nova Estado</a>
</div>

<form method="POST" action="">
    @Html.ValidationSummary(true)
    <fieldset>
        
        <input id="Id" name="Id" type="hidden" value="@Model.CD_ESTADO" />
        
        <legend>Nova Estado</legend>
        <div class="form-group">
            <label for="Nome">Nome da Estado</label>
            <input id="Nome" name="Nome" type="text" value="@Model.DS_ESTADO" class="form-control" placeholder="Digite o nome da sala">
            @Html.ValidationMessageFor(x => x.DS_ESTADO)
        </div>

        <hr />
        <p>
            <button type="submit" class="btn btn-sm btn-info">Salvar</button>
            <a href="@Url.Action("Index","Home")">Cancelar</a>
        </p>
    </fieldset>
</form>

Bludata/Bludata/Views/Estado/Excluir.cshtml
@model MySqlASPNetMVC.Models.Estado
@{
    ViewBag.Title = "Excluir esta Estado?";
}

<div class="page-header">
    <h1>Estado <small>organize o cadastro de estados</small></h1>
    <a href="@Url.Action("Cadastrar","Home")" class="btn btn-sm btn-primary">Nova Estado</a>
</div>
<div class="alert alert-danger">
    <strong>Atenção!</strong> Deseja realmente excluir este registro?
</div>
<fieldset>
    <legend>Detalhes da Estado</legend>
    <div class="form-group">
        <strong>Nome: </strong> @Model.DS_ESTADO
    </div>
</fieldset>

<hr />
<form method="POST" action="">
    <input type="hidden" value="@Model.CD_ESTADO" name="Id" id="Id" />
    <p>
        <button type="submit" class="btn btn-sm btn-info">Excluir</button>
        <a href="@Url.Action("Index","Home")">Cancelar</a>
    </p>
</form>

Bludata/Bludata/Views/Estado/Index.cshtml
@model  IEnumerable<MySqlASPNetMVC.Models.Estado>
@{
    ViewBag.Title = "Estado";
}

<div class="page-header">
    <h1>Estado <small>organize o cadastro de Estados</small></h1>
    <a href="@Url.Action("Cadastrar","Estado")" class="btn btn-sm btn-primary">Nova Estado</a>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Estados Cadastradas
            </div>
            <div class="panel-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nome da Estado</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ var x = 0;}
                        @foreach (var item in Model)
                        {
                            x++;
                            <tr>
                                <td style="width: 50px">@x</td>
                                <td><a href="@Url.Action("Detalhe", "Estado", new { Id = item.CD_ESTADO })">@item.DS_ESTADO</a></td>
                                <td style="width: 100px">
                                    <a href="@Url.Action("Editar", "Estado", new { Id = item.CD_ESTADO })" class="btn btn-info btn-sm">
                                    <span class="glyphicon glyphicon-edit"></span>
                                    </a>
                                    <a href="@Url.Action("Excluir", "Estado", new { Id = item.CD_ESTADO })" class="btn btn-danger btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>