Bludata/Bludata/Controllers/EmpresaController.cs
using MySqlASPNetMVC.Aplicacao;
using MySqlASPNetMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MySqlASPNetMVC.Controllers
{
    public class EmpresaController : Controller
    {
        private EmpresaAplicacao EmpresaAplicacao;
        private EstadoAplicacao EstadoAplicacao;
        public EmpresaController()
        {
            EmpresaAplicacao = new EmpresaAplicacao();
            EstadoAplicacao = new EstadoAplicacao();
        }
        public ActionResult Index()
        {
            var results = EmpresaAplicacao.ListarTodos();

            return View(results.ToList());
        }

        public ActionResult Cadastrar()
        {
            var estado = EstadoAplicacao.ListarTodos().Select(c => new
            {
                CD_ESTADO = c.Id,
                DS_ESTADO = c.DS_ESTADO

            }).ToList();

            ViewBag.Estados = new SelectList(estado, "CD_ESTADO", "DS_ESTADO");

            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                EmpresaAplicacao.Salvar(empresa);
                return RedirectToAction("Index");
            }
            
            return View();
        }

        public ActionResult Editar(int Id)
        {
            var estado = EstadoAplicacao.ListarTodos().Select(c => new
            {
                CD_ESTADO = c.Id,
                DS_ESTADO = c.DS_ESTADO

            }).ToList();

            ViewBag.Estados = new SelectList(estado, "CD_ESTADO", "DS_ESTADO");

            var empresa = EmpresaAplicacao.ListarPorId(Id);
            if (empresa == null)
                return HttpNotFound();
            return View(empresa);
        }

        [HttpPost]
        public ActionResult Editar(Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                EmpresaAplicacao.Salvar(empresa);
                return RedirectToAction("Index");
            }
            return View(empresa);
        }

        public ActionResult Detalhe(int id)
        {
            var empresa = EmpresaAplicacao.ListarPorId(id);

            if (empresa == null)
                return HttpNotFound();

            return View(empresa);
        }

        public ActionResult Excluir(int id)
        {
            var empresa = EmpresaAplicacao.ListarPorId(id);

            if (empresa == null)
                return HttpNotFound();

            return View(empresa);
        }

        [HttpPost, ActionName("Excluir")]
        public ActionResult ConfirmarExcluir(int id)
        {
            EmpresaAplicacao.Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

Bludata/Bludata/Controllers/FornecedorController.cs
using MySqlASPNetMVC.Aplicacao;
using MySqlASPNetMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MySqlASPNetMVC.Controllers
{
    public class FornecedorController : Controller
    {
        private FornecedorAplicacao FornecedorAplicacao;
        private EmpresaAplicacao EmpresaAplicacao;
        public FornecedorController()
        {
            FornecedorAplicacao = new FornecedorAplicacao();
            EmpresaAplicacao = new EmpresaAplicacao();
        }
        public ActionResult Index()
        {
            var lista = FornecedorAplicacao.ListarTodos();
            return View(lista);
        }

        public ActionResult Cadastrar()
        {
            var Empresas = EmpresaAplicacao.ListarTodos().Select(c => new
            {
                CD_EMPRESA = c.Id,
                NOME_FANTASIA = c.NOME_FANTASIA

            }).ToList();

            ViewBag.Empresas = new SelectList(Empresas, "CD_EMPRESA", "NOME_FANTASIA");

            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Fornecedor fornecedor)
        {
            if (ModelState.IsValid)
            {
                FornecedorAplicacao.Salvar(fornecedor);
                return RedirectToAction("Index");
            }
            return View(fornecedor);
        }

        public ActionResult Editar(int Id)
        {
            var Empresas = EmpresaAplicacao.ListarTodos().Select(c => new
            {
                CD_EMPRESA = c.Id,
                NOME_FANTASIA = c.NOME_FANTASIA

            }).ToList();

            ViewBag.Empresas = new SelectList(Empresas, "CD_EMPRESA", "NOME_FANTASIA");

            var fornecedor = FornecedorAplicacao.ListarPorId(Id);
            if (fornecedor == null)
                return HttpNotFound();

            return View(fornecedor);
        }

        [HttpPost]
        public ActionResult Editar(Fornecedor fornecedor)
        {
            if (ModelState.IsValid)
            {
                FornecedorAplicacao.Salvar(fornecedor);
                return RedirectToAction("Index");
            }
            return View(fornecedor);
        }

        public ActionResult Detalhe(int id)
        {
            var fornecedor = FornecedorAplicacao.ListarPorId(id);

            if (fornecedor == null)
                return HttpNotFound();

            return View(fornecedor);
        }

        public ActionResult Excluir(int id)
        {
            var fornecedor = FornecedorAplicacao.ListarPorId(id);

            if (fornecedor == null)
                return HttpNotFound();

            return View(fornecedor);
        }

        [HttpPost, ActionName("Excluir")]
        public ActionResult ConfirmarExcluir(int id)
        {
            FornecedorAplicacao.Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

Bludata/Bludata/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Exemplo de uso do MySQL com ASP.Net MVC</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Empresas", "Index", "Empresa", new { area = "" }, new { @class = "navbar-brand" }))
                @Html.ActionLink("Fornecedores", "Index", "Fornecedor", new { area = "" }, new { @class = "navbar-brand" }))
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index","Home")">Home</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SISTEMA BLUDATA - <a href="#">AMIN KARIMI</a></p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>